// MODAL LOGIN
export const TOOGLE = `MODAL: TOOGLE`;
export const TOOGLE_LOGIN = `MODAL: TOOGLE_LOGIN`;
export const SIGNUP_SUCCESS = `MODAL: SIGNUP_SUCCESS`;
export const SIGNIN_SUCCESS = `MODAL: SIGNIN_SUCCESS`;
export const SIGNIN_ERROR = `MODAL: SIGNIN_ERROR`;
export const CLEAR_NOTIFICATION = `MODAL: CLEAR_NOTIFICATION`;

export const EXAMPLE = `EXAMPLE`;
